-- AUTO-GENERATED by tools/wowhead_scraper.py
-- Generated: 2026-04-10 17:19:23
-- Total NPCs: 50

local ADDON_NAME = "ImABigDeal"
local IABD = _G[ADDON_NAME]

-- Merge wowhead data into nameOverrides
for name, entry in pairs({
  ["arcanist baladrialle &lt;veteran honor quartermaster&gt;"] = { 2, "Veteran Honor Quartermaster", "Veteran Honor Quartermaster." },
  ["arcanist peridris &lt;honor quartermaster&gt;"] = { 2, "Honor Quartermaster", "Honor Quartermaster." },
  ["argent quartermaster &lt;the argent dawn&gt;"] = { 2, "The Argent Dawn", "The Argent Dawn." },
  ["argex irongut &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["argex irongut &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["blacktalon quartermaster &lt;supplier to the black prince&gt;"] = { 2, "Supplier to the Black Prince", "Supplier to the Black Prince." },
  ["blacktalon quartermaster &lt;supplier to the black prince&gt;"] = { 2, "Supplier to the Black Prince", "Supplier to the Black Prince." },
  ["blood guard zar'shi &lt;honor quartermaster&gt;"] = { 2, "Honor Quartermaster", "Honor Quartermaster." },
  ["bloodguard nargol &lt;orgrimmar quartermaster&gt;"] = { 2, "Orgrimmar Quartermaster", "Orgrimmar Quartermaster." },
  ["brave chuata &lt;siege of orgrimmar quartermaster&gt;"] = { 2, "Siege of Orgrimmar Quartermaster", "Siege of Orgrimmar Quartermaster." },
  ["brave tuho &lt;thunder bluff quartermaster&gt;"] = { 2, "Thunder Bluff Quartermaster", "Thunder Bluff Quartermaster." },
  ["captain dirgehammer &lt;conquest quartermaster&gt;"] = { 2, "Conquest Quartermaster", "Conquest Quartermaster." },
  ["champion uru'zin &lt;darkspear quartermaster&gt;"] = { 2, "Darkspear Quartermaster", "Darkspear Quartermaster." },
  ["commander aliocha segard [icecrown raid] &lt;argent crusade quartermaster&gt;"] = { 2, "Argent Crusade Quartermaster", "Argent Crusade Quartermaster." },
  ["doris volanthius &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["doris volanthius &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["ecton brasstumbler &lt;honor quartermaster&gt;"] = { 2, "Honor Quartermaster", "Honor Quartermaster." },
  ["evee copperspring &lt;conquest quartermaster&gt;"] = { 2, "Conquest Quartermaster", "Conquest Quartermaster." },
  ["knight-lieutenant t'maire sydes &lt;honor quartermaster&gt;"] = { 2, "Honor Quartermaster", "Honor Quartermaster." },
  ["knight-lieutenant t'maire sydes &lt;northrend armor quartermaster&gt;"] = { 2, "Northrend Armor Quartermaster", "Northrend Armor Quartermaster." },
  ["lieutenant tristia &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["lieutenant tristia &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["magister saremvir &lt;honor quartermaster&gt;"] = { 2, "Honor Quartermaster", "Honor Quartermaster." },
  ["magistrix feyrina &lt;veteran honor quartermaster&gt;"] = { 2, "Veteran Honor Quartermaster", "Veteran Honor Quartermaster." },
  ["magistrix nizara &lt;silvermoon city quartermaster&gt;"] = { 2, "Silvermoon City Quartermaster", "Silvermoon City Quartermaster." },
  ["nargle lashcord &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["nargle lashcord &lt;glorious conquest quartermaster&gt;"] = { 2, "Glorious Conquest Quartermaster", "Glorious Conquest Quartermaster." },
  ["quartermaster dernhak &lt;general goods&gt;"] = { 2, "General Goods", "General Goods." },
  ["quartermaster logan &lt;warfront token redemption&gt;"] = { 2, "Warfront Token Redemption", "Warfront Token Redemption." },
  ["quartermaster rahm &lt;general goods &amp; repairs&gt;"] = { 2, "General Goods & Repairs", "General Goods & Repairs." },
  ["quartermaster rallings &lt;general goods&gt;"] = { 2, "General Goods", "General Goods." },
  ["quartermaster rutherford &lt;general goods&gt;"] = { 2, "General Goods", "General Goods." },
  ["quartermaster winfred &lt;general goods&gt;"] = { 2, "General Goods", "General Goods." },
  ["sergeant kien &lt;jewelcrafting quartermaster&gt;"] = { 2, "Jewelcrafting Quartermaster", "Jewelcrafting Quartermaster." },
  ["sergeant thunderhorn &lt;apprentice armor quartermaster&gt;"] = { 2, "Apprentice Armor Quartermaster", "Apprentice Armor Quartermaster." },
  ["sergeant thunderhorn &lt;conquest quartermaster&gt;"] = { 2, "Conquest Quartermaster", "Conquest Quartermaster." },
  ["xazi smolderpipe &lt;conquest quartermaster&gt;"] = { 2, "Conquest Quartermaster", "Conquest Quartermaster." },
  ["zom bocom &lt;honor quartermaster&gt;"] = { 2, "Honor Quartermaster", "Honor Quartermaster." },
}) do
  if not IABD.nameOverrides[name] then
    IABD.nameOverrides[name] = entry
  end
end