-- AUTO-GENERATED by tools/wowhead_scraper.py
-- Generated: 2026-04-10 17:17:02
-- Total NPCs: 1

local ADDON_NAME = "ImABigDeal"
local IABD = _G[ADDON_NAME]

-- Merge wowhead data into nameOverrides
for name, entry in pairs({
  ["lor'themar theron &lt;regent lord of quel'thalas&gt;"] = { 2, "Regent Lord of Quel'Thalas", "Regent Lord of Quel'Thalas. Alliance." },
}) do
  if not IABD.nameOverrides[name] then
    IABD.nameOverrides[name] = entry
  end
end