#!/usr/bin/env python3
"""
Scans the customSounds folder for .ogg files and generates soundlist.lua.
Run this after adding or converting new sounds.

Usage: python3 scan.py
"""

import os
import glob

script_dir = os.path.dirname(os.path.abspath(__file__))
addon_dir = os.path.dirname(script_dir)

# Find all .ogg files in this folder
ogg_files = sorted(glob.glob(os.path.join(script_dir, "*.ogg")))

# Generate the Lua file
soundlist_path = os.path.join(addon_dir, "soundlist.lua")
with open(soundlist_path, "w") as f:
    f.write("-- AUTO-GENERATED by customSounds/scan.py\n")
    f.write("-- Run scan.py after adding new .ogg files\n\n")
    f.write('local CP = _G["CritPopup"]\n')
    f.write("if not CP then return end\n\n")
    f.write("CP.scannedSounds = {\n")
    for ogg in ogg_files:
        filename = os.path.basename(ogg)
        f.write(f'  "{filename}",\n')
    f.write("}\n")

print(f"Found {len(ogg_files)} .ogg files:")
for ogg in ogg_files:
    print(f"  {os.path.basename(ogg)}")
print(f"\nGenerated: {soundlist_path}")
